runtime: python37

handlers:
- url: /static/css
  static_dir: static/css
  
- url: /static/js
  static_dir: static/js
  
- url: /static/images
  static_dir: static/images
  
- url: /(.*\.(html|css|js|png|jpg|gif|woff|woff2|ttf|svg|eot))
  static_files: \1
  upload: ./(.*\.(html|css|js|png|jpg|gif|woff|woff2|ttf|svg|eot))
  
- url: /.*
  static_files: index.html
  upload: index.html
